import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/shared/navbar'
import NextAuthProvider from '@/providers/NextAuthProvider'
import { ReactQueryProvider } from '@/providers/ReactQueryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <NextAuthProvider>
        <html lang="en">
          <body className={inter.className}>
            <Navbar />
            <main className='bg-gray-50 h-screen'>
              {children}
            </main>
          </body>
        </html>
      </NextAuthProvider>
    </ReactQueryProvider>
  )
}
